# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Billy < Formula
  desc "Local AI coding assistant powered by Ollama. No subscription required."
  homepage "https://github.com/jd4rider/billy-app"
  version "0.1.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jd4rider/billy-app/releases/download/v0.1.1-alpha/billy_darwin_amd64.tar.gz"
      sha256 "74758332ba3e829efe898bedb13ccf4521a9ce7afaf9853474287e08cffb183e"

      define_method(:install) do
        bin.install "billy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jd4rider/billy-app/releases/download/v0.1.1-alpha/billy_darwin_arm64.tar.gz"
      sha256 "e3ed9c1ccb925ba576f81172db5fd4f9e54ce5325f24375457d06ffb5cf791d6"

      define_method(:install) do
        bin.install "billy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jd4rider/billy-app/releases/download/v0.1.1-alpha/billy_linux_amd64.tar.gz"
      sha256 "6b2b29e738e56058796f600b9fcc14bcccb3539a74cd975a57ffa8a0e6e474f9"
      define_method(:install) do
        bin.install "billy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jd4rider/billy-app/releases/download/v0.1.1-alpha/billy_linux_arm64.tar.gz"
      sha256 "ed9ccd3422fd41fff21c099b961fd17c5fdac8a81e68f8914de2cff895a0c009"
      define_method(:install) do
        bin.install "billy"
      end
    end
  end

  test do
    system "#{bin}/billy", "--version"
  end
end
